# Generated by Django 3.2.8 on 2022-01-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', null=True),
        ),
    ]
