# Generated by Django 3.2.8 on 2022-02-08 09:40

from django.db import migrations, models
import recipes.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeingredientimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientimage',
            name='image',
            field=models.ImageField(upload_to=recipes.utils.recipe_ingredient_image_upload_handler),
        ),
    ]
